# Generated by Django 5.2.4 on 2025-07-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('scheduled_time', models.DateTimeField()),
                ('service', models.CharField(max_length=100)),
            ],
        ),
    ]
