# Generated by Django 5.2.4 on 2025-07-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='customer', max_length=20),
        ),
    ]
